### ISSUE TITLE
x230 UEFI BIOS 1.13

### ISSUE THREAD

**Issue by y0d4a** [gch1p/thinkpad-bios-software-flashing-guide#12]
Dear,

is it safe to try to unlock BIOS on x230 model with uefi bios 1.13?

tnx.

**Comment by gch1p** [comment]
Well, it should work. But I'd recommend updating BIOS anyway because it will also update EC firmware. Or update EC separately, if you can (I guess https://github.com/hamishcoleman/thinkpad-ec project may help with that).
