### ISSUE TITLE
Downgrading: "BIOS image is equal or older than ROM"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [gch1p/thinkpad-bios-software-flashing-guide#13]
I edited AUTOEXEC.BAT according to induction:

```
@ECHO OFF
PROMPT $p$g
cd c:\flash
dosflash.exe /sd /file G1ETA4WW\$01D2000.FL1
```

But:

![IMG_20211204_040639.jpg](https://user-images.githubusercontent.com/3514015/144690798-cd61e539-d9f9-4ed4-ba12-ec3c20d5fa0d.jpg)

Downloaded BIOS for t430: 2.64

My BIOS: 2.74

**Comment by gch1p** [comment]
There is an option that allows downgrading in bios settings, perhaps you forgot to enable it?

**Comment by vitaly-zdanevich** [comment]
Thank you, I forgot it:

![IMG_20211204_042941.jpg](https://user-images.githubusercontent.com/3514015/144691764-a6f67a78-11dc-498d-966f-c82b5e42ce21.jpg)

**Comment by gch1p** [comment]
Does it work now?

**Comment by vitaly-zdanevich** [comment]
Yes, thank you, flashing was successful.
