### ISSUE TITLE
Minor clarifications / info?

### ISSUE THREAD

**Issue by a-hurst** [gch1p/thinkpad-bios-software-flashing-guide#3]
So I just made it through the guide (massive thanks for making it!) and thought I might share some notes on my experience might help future users or inform future updates:

* First, the USB I used for flashing the downgrade BIOS onto was apparently GPT partitioned, which made it refuse to boot when in Legacy Mode. After changing the partition table to MBR and re-dd'ing the image, everything worked fine. Maybe a warning or a command for making the USB's table MBR could be added to the guide?

* My Linux distro (BunsenLabs Helium, based on Debian Stretch) had a flashrom version older than 1.0, meaning it lacked the `--ifd` flag used in the backup command in the guide. To get around this, I ended up doing a whole song-and-dance with linuxbrew and compiling from source to get it to work. A note about this, and a recommendation of a distro that has a new enough flashrom version, would be helpful here. Also, even after compiling a working `flashrom`, it wouldn't work on my system until I rebooted and added `iomem=relaxed` to my kernel arguments with GRUB when booting, since apparently that's needed sometimes.

* CHIPSEC worked largely fine, but the `chipsec_main` and `chipsec_util` commands in the guide didn't work unmodified for me (gave me a "command not found" error): to fix, I just subbed in `python chipset_main.py` and `python chipsec_util.py` (respectively) and it all worked fine.

* On my system, I'd inadvertently installed Linux in legacy boot mode so `/sys/firmware/efi` didn't exist and I wasn't sure how to fix it. The workaround here was to take my BIOS-downgrade USB, re-partition as GPT, and install the rEFInd boot manager to it. After booting from that (it detected my linux install automatically), the folder was present and all the BIOS patches worked smoothly.

Hope this is helpful!

**Comment by gch1p** [comment]
Thank you for using the guide and sharing these notes! I'm glad you didn't brick your laptop during the process.

I'm a bit busy with other projects at the moment, but I have plans to update the guide anyway (need to include info from #1, etc), I hope I'll do it before the end of this year.

**Comment by LinuxOnTheDesktop** [comment]
Also - if I may - I wonder what happens if Lenovo ever offers a BIOS update to one of the old machines at issue and, relatedly, whether - after flashing CoreBoot - `fwupdmgr` will contiue to work.

**Comment by gch1p** [comment]
> what happens if Lenovo ever offers a BIOS update to one of the old machines at issue

We'll see.

> whether - after flashing CoreBoot - `fwupdmgr` will contiue to work. 

I believe it won't.
