### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by shaanek** [gch1p/thinkpad-bios-software-flashing-guide#4]
Thank you for making this! 

I was mostly interested just in the downgrading BIOS section for an X230.  Do you know if there should be any challenge to go from 2.77 (the latest) down to 2.75/2.74?  Following the list, my USB / X230 will just sit display Lenovo Group Limited but never commence flashing.

**Comment by gch1p** [comment]
Hi. Have you changed boot mode to BIOS only?

**Comment by shaanek** [comment]
Yes, I have as follows,
Boot Mode is set to Legacy Only 

Under UEFI BIOS Update,
Flash BIOS Enabled
Secure Rollback Prevention Disabled

Is there a way to check the USB Drive? It is partitioned as MBR with nothing else on it.
Obviously at 2.77 I cannot flash for an X220 keyboard, with 2.75 I could.

**Comment by gch1p** [comment]
And you're sure you don't have `command.com` line in your `autoexec.bat`?
No ideas, but I can test on my X230.

**Comment by shaanek** [comment]
Yes autoexec.bat has been modified as mentioned.  

I'm thinking it is either a USB Drive issue or perhaps 2.77 not allowing anything.  I will try another USB drive and wipe, would be curious to see if it works on your X230 from 2.77.

*Edit*

Wiped USB and verified on disks.  Re-wrote 2.74 this time and it seems to be working.  Will update if it succeeds.

**Comment by shaanek** [comment]
I've successfully reverted back to 2.74 from 2.77.  Thank you for this!

I'm guessing my original USB Flash did not take correctly.

**Comment by gch1p** [comment]
Okay, great :)
