### ISSUE TITLE
Error on BIOS backup

### ISSUE THREAD

**Issue by martins-pukitis** [gch1p/thinkpad-bios-software-flashing-guide#6]
Hi.
I have T430 with BIOS version 2.82. Should BIOS backup command work?

> $ sudo flashrom -p internal -r bios_backup.rom --ifd -i bios
[sudo] password for lieta: 
flashrom  on Linux 5.3.0-26-generic (x86_64)
flashrom is free software, get the source code at https://flashrom.org
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
========================================================================
WARNING! You seem to be running flashrom on an unsupported laptop.
Laptops, notebooks and netbooks are difficult to support and we
recommend to use the vendor flashing utility. The embedded controller
(EC) in these machines often interacts badly with flashing.
See the manpage and https://flashrom.org/Laptops for details.
If flash is shared with the EC, erase is guaranteed to brick your laptop
and write may brick your laptop.
Read and probe may irritate your EC and cause fan failure, backlight
failure and sudden poweroff.
You have been warned.
========================================================================
Aborting.
Error: Programmer initialization failed.

**Comment by gch1p** [comment]
Hi.
Try `sudo flashrom -p internal:laptop=force_I_want_a_brick -r bios_backup.rom --ifd -i bios` (don't worry it won't brick it)

**Comment by martins-pukitis** [comment]
Is it safe?

**Comment by martins-pukitis** [comment]
It worked, thanks.
I won't be able to write it back with

> sudo flashrom -p internal:laptop=force_I_want_a_brick -w bios_backup.rom --ifd -i bios

unless I first switch to BIOS version 2.64, right?

**Comment by gch1p** [comment]
Well, the main purpose of having a backup is to be able to flash it externally (by connecting external SPI programmer to the chip) in case you bricked the machine completely. But you can also flash it from vulnerable BIOS version, yes.

**Comment by aeri** [comment]
Failed this method for me also with forced method, X230T with 2.58 and flashrom v1.0 i got this error:

```
Found chipset "Intel QM77".
Enabling flash write... Error accessing ICH RCRB, 0x4000 bytes at 0x00000000fed1c000
/dev/mem mmap failed: Operation not permitted
FAILED!
FATAL ERROR!
Error: Programmer initialization failed.
```

**Comment by gch1p** [comment]
> Failed this method for me also with forced method, X230T with 2.58 and flashrom v1.0 i got this error:
> 
> ```
> Found chipset "Intel QM77".
> Enabling flash write... Error accessing ICH RCRB, 0x4000 bytes at 0x00000000fed1c000
> /dev/mem mmap failed: Operation not permitted
> FAILED!
> FATAL ERROR!
> Error: Programmer initialization failed.
> ```

You need to boot with `iomem=relaxed`.

**Comment by aeri** [comment]
> > Failed this method for me also with forced method, X230T with 2.58 and flashrom v1.0 i got this error:
> > ```
> > Found chipset "Intel QM77".
> > Enabling flash write... Error accessing ICH RCRB, 0x4000 bytes at 0x00000000fed1c000
> > /dev/mem mmap failed: Operation not permitted
> > FAILED!
> > FATAL ERROR!
> > Error: Programmer initialization failed.
> > ```
> 
> You need to boot with `iomem=relaxed`.

Thank you, it worked with forced mode.
