### ISSUE TITLE
Error: image size does not match the flash chip's size

### ISSUE THREAD

**Issue by mocart2** [gch1p/thinkpad-bios-software-flashing-guide#8]
Hi, i try to jailbreak my t430, but when i try it i have error:
![IMG_20210131_233035](https://user-images.githubusercontent.com/10042982/106397233-56eaf500-641d-11eb-871c-dae33d98f034.jpg)
My diag information:
![IMG_20210131_233131](https://user-images.githubusercontent.com/10042982/106397252-6d914c00-641d-11eb-9d4e-aa6a738f0538.jpg)
P.s. i'm flashing by zalman virtual cdrom (odd)

**Comment by gch1p** [comment]
Well... did you read those errors?

You have some I/O issues with that CD and `flashrom` says that it gets 0 bytes image.

**Comment by mocart2** [comment]
I think

> Well... did you read those errors?
> 
> You have some I/O issues with that CD and `flashrom` says that it gets 0 bytes image.

Ok, thanks, i try to write image to other usb flash drive
