### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [gch1p/thinkpad-bios-software-flashing-guide#9]
Hello!

Could you please add information about license of this repository — is it allowed to copy, change and use the code and documentation in any purpose?
It would be great to see any popular open source license.
As I see, you have 11 forks — I think they all will be happy.

**Comment by gch1p** [comment]
OK.
I contributed a large portion of this repo to coreboot documentation, which is licensed under CC-BY 4.0, so I think it's fare to license whole repo under CC-BY 4.0.
